FROM alpine:latest

RUN apk add --no-cache perl git perl-net-ftp perl-time-hires perl-io-socket-ssl

RUN git clone https://github.com/alsotoes/dotdotpwn /opt/dotdotpwn

WORKDIR /opt/dotdotpwn

ENTRYPOINT ["perl", "dotdotpwn.pl"]
