FROM alpine:latest

RUN apk add --no-cache perl git perl-io-socket-ssl perl-libwww

RUN git clone https://github.com/alsotoes/dotdotpwn /opt/dotdotpwn

WORKDIR /opt/dotdotpwn

ENTRYPOINT ["perl", "dotdotpwn.pl"]
