package crypto

import (
	"crypto/sha256"
	"fmt"
	"math/big"

	"github.com/bytemare/crypto"
)

// OPRFSharePair holds a derived Shamir share for one daemon: the evaluation
// point (share index) and the encoded scalar share. Shares are generated by a
// dealer so that no daemon (or client) can recompute the others from its own
// key material.
type OPRFSharePair struct {
	// ShareIndex is the Shamir evaluation point (1-based) for this share.
	ShareIndex int
	// Share is the encoded scalar share value.
	Share []byte
}

// GenerateOPRFShares splits a freshly generated random OPRF secret into n
// Shamir shares with the given threshold t (1 <= t <= n). Each returned share
// is destined for one daemon. The full secret is never returned, so no single
// holder can evaluate the OPRF on its own; any t distinct shares interpolate
// to the same f(0) and therefore the same content key.
func GenerateOPRFShares(t, n int) ([]OPRFSharePair, error) {
	if t < 1 || n < t {
		return nil, fmt.Errorf("oprf: invalid threshold %d for %d shares", t, n)
	}

	coeffs := make([]*crypto.Scalar, t)
	for i := range coeffs {
		coeffs[i] = oprfGroup.NewScalar().Random()
	}
	// coeffs[0] is f(0), the secret. It is never serialized or returned.

	shares := make([]OPRFSharePair, n)
	for point := 1; point <= n; point++ {
		// f(point) = sum_{k} coeffs[k] * point^k
		out := oprfGroup.NewScalar().Zero()
		p := oprfGroup.NewScalar().One()
		for _, c := range coeffs {
			term := p.Copy().Multiply(c)
			out = out.Copy().Add(term)
			p = p.Copy().Multiply(scalarFromInt(point))
		}
		shares[point-1] = OPRFSharePair{
			ShareIndex: point,
			Share:      out.Copy().Encode(),
		}
	}
	return shares, nil
}

// ScalarLength returns the encoded byte size of an OPRF scalar share.
func ScalarLength() int { return oprfGroup.ScalarLength() }

// This file implements a threshold Oblivious PRF (OPRF) over Ristretto255
// used for confidential dedup. The dedup tag (content hash) of a plaintext is
// hashed to a group point; the final OPRF output (a group element) is seeded
// from a split secret so that no single daemon can evaluate it on its own.
//
// The operation is additive: every operation below is over the Ristretto255
// prime-order group, so Element.Multiply(s) is the element multiplied by scalar
// s, and Element.Add sums two elements. The secret split is performed with a
// degree-(threshold-1) Shamir polynomial f(x) = c0 + c1*x + ... evaluated at
// distinct non-zero points, one per daemon. Any `threshold` shares recover the
// same f(0), so the derived content key is deterministic across every quorum.

const (
	// oprfDST is the domain separation tag for hashing the dedup tag into the
	// group and for deriving the Shamir coefficients. It must exceed 16 bytes.
	oprfDST = "momo/oprf/threshold-ristretto255-sha512"
)

// oprfGroup is the prime-order group used by the threshold OPRF.
var oprfGroup = crypto.Ristretto255Sha512

// OPRFEvaluation is one daemon's response to a blinded OPRF query: the
// interpolated share index and its evaluation of the blinded point.
type OPRFEvaluation struct {
	// ShareIndex is the Shamir evaluation point (daemon index + 1) used.
	ShareIndex int
	// Eval is the encoded group element result of the share evaluation.
	Eval []byte
}

// OPRFBlind hashes the dedup tag into the group and blinds it with a random
// scalar. It returns the encoded blinded element (sent to the daemons) and the
// encoded blind scalar (kept secret by the client).
func OPRFBlind(tag []byte) (blinded []byte, blind []byte, err error) {
	if len(tag) == 0 {
		return nil, nil, fmt.Errorf("oprf: empty tag input")
	}
	t := oprfGroup.HashToGroup(tag, []byte(oprfDST))
	r := oprfGroup.NewScalar().Random()
	blindedElem := t.Copy().Multiply(r)
	blindScalar := r.Copy()
	return blindedElem.Encode(), blindScalar.Encode(), nil
}

// OPRFEvaluateShare evaluates a blinded OPRF point under a single daemon's
// share. shareScalar is the encoded scalar share, blinded is the encoded blinded
// element from the client. It returns the encoded evaluated group element.
func OPRFEvaluateShare(shareScalar, blinded []byte) ([]byte, error) {
	share, err := decodeScalar(shareScalar)
	if err != nil {
		return nil, err
	}
	blindedElem, err := decodeElement(blinded)
	if err != nil {
		return nil, err
	}
	return blindedElem.Copy().Multiply(share).Encode(), nil
}

// OPRFCombineUnblind recovers the OPRF output from `threshold` or more share
// evaluations by interpolating the Shamir secret at f(0), then unblinds using
// the client's blind scalar. The output is the content key (SHA-256 of the
// encoded group element). It fails closed (returns an error) when fewer than
// threshold evaluations are supplied.
func OPRFCombineUnblind(evaluations []OPRFEvaluation, blind []byte, threshold int) ([]byte, error) {
	if threshold < 1 {
		return nil, fmt.Errorf("oprf: threshold must be >= 1")
	}
	if len(evaluations) < threshold {
		return nil, fmt.Errorf("oprf: only %d evaluations, need %d", len(evaluations), threshold)
	}
	if threshold == 1 {
		// Simple case: a single evaluation requires no interpolation.
		if err := verifyUniqueEvaluations(evaluations); err != nil {
			return nil, err
		}
		return oprfFinalize(evaluations[0].Eval, blind)
	}

	// Compute Lagrange coefficients L_i(0) = prod_{j!=i} (x_j)/(x_j - x_i).
	// Points x_i = ShareIndex.
	coefficients, err := lagrangeAtZero(evaluations)
	if err != nil {
		return nil, err
	}

	// combined = sum_i coeff_i * eval_i  (additive group).
	var combined *crypto.Element
	for i, eval := range evaluations {
		e := oprfGroup.NewElement()
		if err := e.Decode(eval.Eval); err != nil {
			return nil, fmt.Errorf("oprf: failed to decode evaluation: %w", err)
		}
		scaled := e.Copy().Multiply(coefficients[i])
		if combined == nil {
			combined = scaled
		} else {
			combined = combined.Copy().Add(scaled)
		}
	}

	return oprfFinalize(combined.Encode(), blind)
}

// oprfFinalize unblinds an interpolated element by the client's blind inverse
// and reduces it to a 32-byte content key.
func oprfFinalize(interpolated []byte, blind []byte) ([]byte, error) {
	e, err := decodeElement(interpolated)
	if err != nil {
		return nil, err
	}
	b, err := decodeScalar(blind)
	if err != nil {
		return nil, err
	}
	bInv := b.Copy().Invert()
	unblinded := e.Copy().Multiply(bInv)
	digest := sha256.Sum256(unblinded.Encode())
	return digest[:], nil
}

// lagrangeAtZero returns the Lagrange basis coefficients evaluated at x=0 for
// the share index set.
func lagrangeAtZero(evaluations []OPRFEvaluation) ([]*crypto.Scalar, error) {
	points := make([]int, len(evaluations))
	for i, e := range evaluations {
		if e.ShareIndex <= 0 {
			return nil, fmt.Errorf("oprf: invalid share index %d", e.ShareIndex)
		}
		points[i] = e.ShareIndex
	}
	if err := verifyUniqueEvaluations(evaluations); err != nil {
		return nil, err
	}

	scalarCache := make(map[int]*crypto.Scalar, len(points))
	for _, p := range points {
		if _, ok := scalarCache[p]; !ok {
			scalarCache[p] = scalarFromInt(p)
		}
	}

	coeffs := make([]*crypto.Scalar, len(points))
	for i, xi := range points {
		num := oprfGroup.NewScalar().One()
		den := oprfGroup.NewScalar().One()
		xiScalar := scalarCache[xi]
		for j, xj := range points {
			if i == j {
				continue
			}
			xjScalar := scalarCache[xj]
			// numerator *= x_j
			num = num.Copy().Multiply(xjScalar)
			// denominator *= (x_j - x_i)
			diff := xjScalar.Copy().Subtract(xiScalar)
			den = den.Copy().Multiply(diff)
		}
		denInv := den.Copy().Invert()
		coeffs[i] = num.Copy().Multiply(denInv)
	}
	return coeffs, nil
}

func scalarFromInt(v int) *crypto.Scalar {
	s := oprfGroup.NewScalar()
	if err := s.SetInt(big.NewInt(int64(v))); err != nil {
		panic(fmt.Sprintf("oprf: failed to set integer scalar: %v", err))
	}
	return s
}

// verifyUniqueEvaluations rejects duplicate ShareIndex values, which would allow
// an attacker to reuse a single daemon's evaluation to satisfy the threshold.
func verifyUniqueEvaluations(evaluations []OPRFEvaluation) error {
	seen := make(map[int]struct{}, len(evaluations))
	for _, e := range evaluations {
		if _, ok := seen[e.ShareIndex]; ok {
			return fmt.Errorf("oprf: duplicate share index %d", e.ShareIndex)
		}
		seen[e.ShareIndex] = struct{}{}
	}
	return nil
}

func decodeScalar(b []byte) (*crypto.Scalar, error) {
	if len(b) != oprfGroup.ScalarLength() {
		return nil, fmt.Errorf("oprf: invalid scalar length %d, want %d", len(b), oprfGroup.ScalarLength())
	}
	s := oprfGroup.NewScalar()
	if err := s.Decode(b); err != nil {
		return nil, fmt.Errorf("oprf: failed to decode scalar: %w", err)
	}
	return s, nil
}

func decodeElement(b []byte) (*crypto.Element, error) {
	if len(b) != oprfGroup.ElementLength() {
		return nil, fmt.Errorf("oprf: invalid element length %d, want %d", len(b), oprfGroup.ElementLength())
	}
	e := oprfGroup.NewElement()
	if err := e.Decode(b); err != nil {
		return nil, fmt.Errorf("oprf: failed to decode element: %w", err)
	}
	return e, nil
}
