name: Go

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Benchmark
      run: make benchmark

    - name: E2E Integration Tests
      run: make test-e2e

    - name: Coverage
      run: make coverage

    - name: Upload Coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.out
